services:
  - type: web
    name: vault-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: DEMO_MODE
        value: "true"
      - key: DEFAULT_DURABILITY_POLICY
        value: "QUORUM"
      - key: DEFAULT_READ_POLICY
        value: "ANY_HEALTHY"
      - key: GEMINI_API_KEY
        sync: false
